<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0</TargetFrameworks>
        <RootNamespace>HostPanelPro.Plugins.TechnitiumDNS</RootNamespace>
        <AssemblyName>HostPanelPro.Plugins.TechnitiumDNS.Common</AssemblyName>
        <LangVersion>latest</LangVersion>
        <Nullable>disable</Nullable>
        <OutputPath>..\bin</OutputPath>
        <RestoreSources Condition="Exists('..\..\..\..\..\Library')">$(RestoreSources);https://api.nuget.org/v3/index.json;..\..\..\..\..\Library</RestoreSources>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HostPanelPro.Providers.Base" Version="1.0.0" />
    </ItemGroup>

</Project>
